# .circleci/config.yml
version: 2
jobs:
  build-and-unit_test:
    macos:
      xcode: "11.0.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Print Homebrew Information
          command: .circleci/scripts/print_homebrew_info.sh

workflows:
  version: 2
  build-and-unit-test:
    jobs:
      - build-and-unit-test
